package com.example.focus_app

import androidx.compose.foundation.layout.*
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.util.*

@Composable
fun FrasesScreen() {
    val frases = listOf(
        "Cree en ti, incluso cuando nadie más lo haga.",
        "Cada dia es una nueva oportunidad para empezar de nuevo.",
        "El éxito se construye con pequeños pasos diarios.",
        "No busques excusas, busca resultados.",
"El fracaso es solo una lección disfrazada.",
"Si puedes soñarlo, puedes lograrlo.",
        "La disciplina vence al talento.",
        "No importa cuántas veces caigas, importa cuántas te levantes.",
"La actitud lo cambia todo.",
        "Hoy es un buen día para avanzar.",
       " La constancia es la clave del éxito.",
       "No esperes el momento perfecto, créalo.",
       "El esfuerzo siempre tiene recompensa.",
        "Las metas no se alcanzan soñando, sino trabajando.",
        "Sé más fuerte que tus excusas.",
       " Todo comienza con una decisión.",
        "La motivación te impulsa, la disciplina te mantiene.",
        "Nunca es tarde para ser quien quieres ser.",
        "Los límites solo existen en tu mente.",
        "Si no te reta, no te cambia.",
        "Tu única competencia eres tú mismo.",
        "La vida premia a los valientes.",
        "No mires atrás, no vas en esa dirección.",
        "Hazlo con pasión o no lo hagas.",
        "Cada error te acerca más al éxito.",
        "Sueña en grande, trabaja duro.",
        "Lo imposible solo tarda un poco más.",
        "Cree en el proceso.",
        "El futuro pertenece a los que se atreven.",
        " La acción vence al miedo.",
        " Un día más, una oportunidad más.",
        " Haz que valga la pena.",
        "No te rindas, lo mejor está por venir.",
        "La energía que das, regresa.",
        "Lo único imposible es lo que no intentas.",
        "Hazlo por ti.",
        "Sé la mejor versión de ti mismo.",
        "Tu esfuerzo hablará por ti.",
        "No busques suerte, trabaja por ella.",
        "Los sueños no tienen fecha de vencimiento.",
        "Cada logro empezó con la decisión de intentarlo.",
        "Aprende, mejora y sigue adelante.",
        "No pares hasta estar orgulloso.",
        "La confianza en uno mismo es poder.",
        "Cada día cuenta.",
        "Haz de tu vida una historia que valga la pena contar.",
        " Tú puedes con más de lo que crees.",
        "La clave está en no rendirse.",
        "No esperes resultados diferentes si haces lo mismo.",
        "Cree, trabaja y logra.",
        "Empieza donde estás, usa lo que tienes, haz lo que puedas.",
        "Cada paso te acerca más a tu meta.",
        "Las grandes cosas toman tiempo.",
        "No te detengas hasta sentirte orgulloso.",
        "El sacrificio de hoy es el éxito de mañana.",
        "Las excusas no queman calorías ni logran sueños.",
        "Sé persistente, no insistente.",
        "Cuando pienses en rendirte, recuerda por qué empezaste.",
        "Todo esfuerzo cuenta.",
        "Tu mentalidad define tu realidad.",
        "No dejes que el miedo decida tu futuro.",
        "Sé valiente, incluso cuando tengas miedo.",
        "Lo mejor aún no ha pasado.",
        "Aprende de ayer, vive hoy, sueña mañana.",
        "Cada fracaso es una oportunidad disfrazada.",
        "La paciencia también es progreso.",
        "La acción genera motivación.",
        "Tú controlas tu actitud.",
        "Nadie dijo que sería fácil, pero valdrá la pena.",
        "Tu mejor inversión eres tú.",
        "El éxito no se mide en palabras, sino en resultados.",
        "El trabajo duro supera al talento cuando el talento no trabaja duro.",
        "Persigue metas, no personas.",
        "Agradece lo que tienes mientras luchas por lo que quieres.",
        "Convierte tus sueños en planes.",
        "La clave del éxito es comenzar.",
        "Aprende a disfrutar del proceso.",
        "Cada día es una oportunidad para mejorar.",
        "Si no te gusta tu historia, cámbiala.",
        "Cuida tu mente tanto como tu cuerpo.",
        "No te compares, cada quien tiene su tiempo.",
        "La diferencia entre ganar y perder está en no rendirse.",
        "El éxito no llega por suerte, llega por constancia.",
        "El dolor es temporal, el orgullo es para siempre.",
        "Los pequeños progresos también son avances.",
        "Hazlo por la versión de ti que no se rindió.",
        "Cada día cuenta, aprovéchalo.",
        "No sueñes con éxito, trabaja por él.",
        "Las metas grandes requieren esfuerzos grandes.",
        "Haz que el mañana te dé las gracias por lo que hiciste hoy.",
        "La motivación te enciende, la disciplina te mantiene.",
        "Los ganadores no nacen, se hacen.",
        "Nadie lo hará por ti, hazlo tú.",
        "La vida recompensa la acción, no la intención.",
        "No busques aprobación, busca progreso.",
        "Convierte tus debilidades en fuerza.",
        "Mantén tu mente enfocada y tu corazón fuerte.",
        "El esfuerzo constante vence al talento dormido.",
        "No pares hasta lograrlo.",
        "Los grandes cambios comienzan con pequeñas decisiones.",
        "Cree en tu visión, aunque otros no la vean.",
        "Tu único límite eres tú.",
        "No esperes resultados si no cambias tus hábitos.",
        "Sueña como si fueras eterno, actúa como si fueras mortal.",
        "Sé agradecido, incluso en los días difíciles.",
        "La vida te pone pruebas para ver si realmente quieres lo que dices.",
        "Tu mente es tu arma más poderosa.",
        "Hazlo con amor, hazlo con propósito.",
        "Tu presente construye tu futuro.",
        "Si quieres resultados distintos, haz cosas distintas.",
        "No hay crecimiento sin incomodidad.",
        "Sé constante, aunque no veas resultados inmediatos.",
        "Los días difíciles te hacen más fuerte.",
        "La disciplina es hacer lo que debes, aunque no tengas ganas.",
        "Tu esfuerzo te define.",
        "Lo que hoy te cuesta, mañana será tu fortaleza.",
        "Nunca te rindas en un mal día.",
        "Las excusas apagan los sueños.",
        "La mejor venganza es el éxito.",
        "No te conformes, mereces más.",
        "Las oportunidades no se esperan, se crean.",
        "Visualiza, actúa y conquista.",
        "Rodéate de personas que te impulsen.",
        "Si puedes imaginarlo, puedes lograrlo.",
        "No vivas de sueños, haz que se cumplan.",
        "El éxito llega cuando la preparación se encuentra con la oportunidad.",
        "Lo que haces hoy marca la diferencia mañana.",
        "No mires el reloj, haz que el tiempo cuente.",
        "Tu energía atrae tu realidad.",
        "Los límites están en tu mente.",
        "La vida premia la acción.",
        "Sé imparable.",
        "Nadie dijo que sería fácil, pero valdrá la pena.",
        "Cada paso es una victoria.",
        "No tengas miedo de empezar de nuevo.",
        "A veces perder es avanzar.",
        "No todos los días son buenos, pero todos enseñan.",
        "La confianza se gana con acción.",
        "Si caes, levántate más fuerte.",
        "Los sueños no se cumplen solos.",
        "No esperes motivación, créala.",
        "Hazlo aunque tengas miedo.",
        "No te desanimes por los resultados lentos, el progreso es progreso.",
        "Todo gran logro comienza con un pequeño paso.",
        "Tu vida cambia cuando tú cambias.",
        "Cada día es una nueva oportunidad para mejorar.",
        "La consistencia crea resultados.",
        "Tu mente puede ser tu aliada o tu enemiga, tú decides.",
        "Haz lo que otros no harán para lograr lo que otros no logran.",
        "Sigue adelante, tu esfuerzo valdrá la pena.",
        "No te detengas hasta cumplir tus metas.",
        "El éxito no se logra por suerte, se construye.",
        "Cada día cuenta, aunque no lo notes.",
        "Las metas grandes comienzan con pasos pequeños.",
        "Lo único que necesitas es empezar.",
        "No te rindas, lo mejor tarda en llegar.",
        "Las cosas buenas requieren tiempo.",
        "Cree más en ti y menos en tus miedos.",
        "Haz lo que amas y ama lo que haces.",
        "La motivación te impulsa, la constancia te lleva.",
        "Tu potencial no tiene límites.",
        "No busques aprobación, busca progreso.",
        "Con esfuerzo y paciencia, todo se logra.",
        "El dolor de la disciplina es menor que el del arrepentimiento.",
        "No esperes resultados si no das lo mejor de ti.",
        "Lo que hoy parece difícil, mañana será tu logro.",
        "El secreto está en no rendirse.",
        "Cada paso hacia adelante cuenta.",
        "Mantén tu enfoque, aunque nadie lo entienda.",
        "Cree en el proceso, incluso cuando no veas resultados.",
        "La acción vence al miedo.",
        "No sueñes con el éxito, trabaja por él.",
        "Las excusas son enemigos del progreso.",
        "Sé constante, incluso cuando no tengas ganas.",
        "Nada cambia si tú no cambias.",
        "Las caídas son parte del camino.",
        "Aprende de los errores y sigue avanzando.",
        "Tu esfuerzo te llevará donde tus sueños te llaman.",
        "No hay éxito sin sacrificio.",
        "No pares hasta sentirte orgulloso.",
        "Las oportunidades llegan cuando trabajas por ellas.",
        "Cada amanecer es una nueva oportunidad.",
        "Sé valiente, incluso cuando dudes.",
        "La disciplina es la base del éxito.",
        "No te compares, tu camino es único.",
        "Si fuera fácil, todos lo harían.",
        "Hazlo por la persona que quieres llegar a ser.",
        "Nunca subestimes tu poder de mejorar.",
        "La constancia crea resultados visibles.",
        "No dejes que el miedo frene tu grandeza.",
        "El éxito no llega de la noche a la mañana.",
        "Cada sacrificio vale la pena.",
        "Persigue metas, no comodidad.",
        "Las pequeñas victorias construyen grandes triunfos.",
        "Agradece cada paso, incluso los difíciles.",
        "La diferencia entre ganar y perder está en la persistencia.",
        "Si no te reta, no te transforma.",
        "El éxito se logra con esfuerzo silencioso.",
        "No mires atrás, tu destino está adelante.",
        "Tu esfuerzo es tu mejor carta de presentación.",
        "Cree, confía y avanza.",
        "Nunca te conformes con menos de lo que mereces.",
        "Sé el cambio que quieres ver en tu vida.",
        "No dejes que la duda te frene.",
        "Tu pasión puede más que tu miedo.",
        "A veces el progreso es silencioso, pero sigue siendo progreso.",
        "Lo que hoy te cuesta, mañana será natural.",
        "Sé fiel a tus metas, incluso en días difíciles.",
        "Tu éxito depende de tu constancia.",
        "No busques atajos, construye tu camino.",
        "Cada día que lo intentas, ya estás ganando.",
        "Las metas se logran con trabajo diario.",
        "No pares hasta que el esfuerzo valga la pena.",
        "A veces perder es parte de avanzar.",
        "Sé agradecido, incluso por los desafíos.",
        "El éxito no se explica, se demuestra.",
        "No temas al fracaso, teme no intentarlo.",
        "No esperes que las cosas cambien si tú no cambias.",
        "Cree en el poder de los pequeños pasos.",
        "Tu futuro depende de lo que hagas hoy.",
        "La única forma de fallar es rendirse.",
        "No dejes que nadie apague tu brillo.",
        "Lo mejor de ti aún está por salir.",
        "Aprende a confiar en tu proceso.",
        "No pierdas tiempo, gana experiencia.",
        "Cada día es una nueva oportunidad para superarte.",
        "El éxito no es suerte, es constancia.",
        "No tengas miedo de empezar de nuevo.",
        "El progreso lento sigue siendo progreso.",
        "La mente positiva atrae resultados positivos.",
        "Si lo puedes imaginar, lo puedes crear.",
        "Lo importante no es la velocidad, es la dirección.",
        "La motivación te pone en marcha, el hábito te mantiene.",
        "Cada esfuerzo tiene su recompensa.",
        "No te detengas, estás más cerca de lo que crees.",
        "Sé fuerte, los días difíciles no duran para siempre.",
        "La confianza te abre puertas.",
        "La perseverancia siempre vence.",
        "El éxito se construye en silencio.",
        "La mejor manera de predecir el futuro es crearlo.",
        "No existe un camino fácil hacia algo que valga la pena.",
        "Cada meta alcanzada comenzó con una idea.",
        "Si lo intentas, puedes fallar; si no lo intentas, ya fallaste.",
        "La constancia convierte sueños en realidad.",
        "No te rindas antes de ver los resultados.",
        "El tiempo premia a los persistentes.",
        "Haz lo que amas, y el éxito te seguirá.",
        "La disciplina hoy es libertad mañana.",
        "No digas “no puedo”, di “aún no puedo”.",
        "El esfuerzo constante crea resultados duraderos.",
        "Mantén la fe incluso cuando el camino sea incierto.",
        "No hay límites para quien no se rinde.",
        "El éxito llega a los que nunca dejan de intentarlo.",
        "Cada día es una nueva oportunidad para ser mejor.",
        "Lo que hoy duele, mañana te hará más fuerte.",
        "Las metas no tienen fecha, solo compromiso.",
        "No te rindas por cansancio, descansa y sigue.",
        "Lo importante no es empezar perfecto, es empezar.",
        "La constancia vence la suerte.",
        "Si fuera imposible, no lo estarías soñando.",
        "La diferencia entre soñar y lograr está en la acción.",
        "No pares por miedo, sigue por pasión.",
        "El éxito no se compra, se construye.",
        "Cree que puedes, y ya estás a medio camino.",
        "No te compares, compite contigo mismo.",
        "Sé más fuerte que tus excusas.",
        "Cada día que sigues, estás ganando terreno.",
        "A veces lo más difícil es lo más necesario.",
        "Si no puedes volar, corre. Si no puedes correr, camina. Pero nunca te detengas.",
        "No subestimes el poder de empezar.",
        "El éxito se gana, no se hereda.",
        "Las dificultades te preparan para cosas grandes.",
        "Enfócate en el progreso, no en la perfección.",
        "Todo logro comienza con la decisión de intentarlo.",
        "No digas “algún día”, di “hoy”.",
        "Lo mejor de la vida viene después de los momentos más difíciles.",
        "No es magia, es trabajo constante.",
        "Los sueños se cumplen con acción.",
        "Si crees en ti, ya ganaste la mitad de la batalla.",
        "Nadie puede detenerte si tú no te detienes.",
        "No busques caminos fáciles, busca resultados reales.",
        "Cada día es una nueva oportunidad para triunfar.",
        "No te des por vencido, los comienzos siempre son difíciles.",
        "La clave está en seguir, incluso cuando nadie te aplaude.",
        "Sé tu propia inspiración.",
        "No pares hasta superar tu versión anterior.",
        "Cada día cuenta para construir tu mejor yo.",
        "Los ganadores se levantan una vez más de las que caen.",
        "Cree en ti tanto como crees en tus sueños.",
        "No busques motivación, crea disciplina.",
        "El éxito es la suma de pequeños esfuerzos repetidos.",
        "Tu esfuerzo hablará más fuerte que tus palabras.",
        "No temas fallar, teme no intentarlo.",
        "Lo que haces hoy define tu mañana.",
        "No hay éxito sin sacrificio ni crecimiento sin esfuerzo.",
        "Cada paso firme te acerca más a tu meta.",
        "Aprende a disfrutar del proceso.",
        "No dejes para mañana lo que puedes lograr hoy.",
        "La paciencia es parte del éxito.",
        "Mantén tus metas claras y tu mente fuerte.",
        "Todo es posible con esfuerzo y fe.",
        "Las excusas no construyen resultados.",
        "Nunca te rindas, los milagros toman tiempo.",
        "El éxito es la suma de persistencia, fe y acción.",
        "Si crees que puedes, ya estás más cerca.",
        "No temas al cambio, abrázalo.",
        "No importa cuántas veces caigas, sino cuántas te levantes.",
        "Cada error te acerca más al acierto.",
        "No pares hasta ver resultados.",
        "El progreso no siempre se nota, pero siempre ocurre.",
        "La clave está en empezar, no en saberlo todo.",
        "No esperes que las cosas sean fáciles, hazte fuerte.",
        "La constancia transforma lo imposible en posible.",
        "Si tu mente puede soñarlo, tu cuerpo puede lograrlo.",
        "No necesitas ser el mejor, solo no rendirte.",
        "La fe sin acción es solo un deseo.",
        "No busques motivación externa, créala tú mismo.",
        "Todo sacrificio tiene su recompensa.",
        "Haz que cada día cuente.",
        "La vida premia a los valientes.",
        "Nadie tiene tu visión, hazla realidad.",
        "Las metas difíciles son las que más valen la pena.",
        "No pares hasta que tus sueños se vuelvan realidad.",
        "Cada paso que das te aleja del ayer.",
        "Sé paciente, las grandes cosas toman tiempo.",
        "La actitud positiva atrae resultados positivos.",
        "Nunca subestimes el poder de un día productivo.",
        "Los ganadores no nacen, se forjan.",
        "Cree, lucha y vence.",
        "El esfuerzo de hoy es el éxito de mañana.",
        "Los retos son oportunidades disfrazadas.",
        "Tu esfuerzo vale la pena, aunque aún no lo veas.",
        "No busques motivación en otros, sé tu motor.",
        "Si te caes siete veces, levántate ocho.",
        "Lo que hoy parece imposible, mañana será tu realidad.",
        "El éxito no tiene fórmula mágica, solo trabajo.",
        "Sé constante, incluso cuando nadie te mire.",
        "No importa cuán lento avances, no te detengas.",
        "Las grandes metas requieren grandes sacrificios.",
        "Nunca te rindas, el éxito está más cerca de lo que crees.",
        "Las acciones hablan más que las intenciones.",
        "No esperes a estar listo, empieza ahora.",
        "Cada día tienes una nueva oportunidad para crecer.",
        "No dejes que el miedo te robe tus sueños.",
        "La constancia siempre vence al talento inconstante.",
        "Tu vida mejora cuando tú mejoras.",
        "El éxito no es suerte, es resultado.",
        "No digas “ojalá”, di “lo haré”.",
        "Cree en el poder del esfuerzo diario.",
        "Nunca pierdas la esperanza.",
        "Todo lo que vale la pena toma tiempo.",
        "La disciplina es el puente entre metas y resultados.",
        "Si puedes soñarlo, puedes lograrlo.",
        "No te detengas por miedo al fracaso.",
        "Haz lo que otros no hacen, para lograr lo que otros no logran.",
        "No pares hasta sentirte orgulloso de ti mismo.",
        "Tu historia aún se está escribiendo, sigue avanzando.",
        "La perseverancia siempre da frutos.",
        "Lo único imposible es lo que no intentas.",
        "El éxito comienza con una decisión.",
        "Cada día es una nueva oportunidad de brillar.",
            "Si crees en ti, todo es posible.",
        "Nunca te rindas, las mejores cosas toman tiempo.",
        "Tú eres tu mejor inversión.",
            "Hoy es un buen día para empezar.",
    )
    // Obtener el día actual del año (1–365)
    val calendar = Calendar.getInstance()
    val dayOfYear = calendar.get(Calendar.DAY_OF_YEAR)

    // Obtener frase según el día
    val fraseDelDia = frases[(dayOfYear - 1) % frases.size]

    // Mostrar la frase en pantalla
    Box(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp),
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = fraseDelDia,
            fontSize = 24.sp,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.primary,
            lineHeight = 32.sp
        )
    }
}


